test 4

diff --git a/.github/workflows/gen_json.yml b/.github/workflows/gen_json.yml
--- a/.github/workflows/gen_json.yml
+++ b/.github/workflows/gen_json.yml
@@ -11,6 +11,15 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Check the previous workflow
+        run: |
+          if [ ${{ github.event.workflow_run.conclusion != 'success' }} ]; then
+            echo "Previous workflow in error"
+            exit 1
+          else
+            echo "Previous workflow OK"
+          fi
+          
       - name: Checkout Repository
         uses: actions/checkout@v2
 
