stop workflow when error

diff --git a/.github/workflows/update_static_html.yml b/.github/workflows/update_static_html.yml
--- a/.github/workflows/update_static_html.yml
+++ b/.github/workflows/update_static_html.yml
@@ -30,6 +30,15 @@ jobs:
       url: ${{ steps.deployment.outputs.page_url }}
     runs-on: ubuntu-latest
     steps:
+      - name: Check the previous workflow
+        run: |
+          if [ ${{ github.event.workflow_run.conclusion == 'success' }} ]; then
+            echo "Previous workflow OK"  
+          else
+            echo "Previous workflow in error"
+            exit 1
+          fi
+
       - name: Checkout
         uses: actions/checkout@v4
       - name: Setup Pages
